title : IntDotaII
description: 'Uma pequena introdução a Dota II'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
